"""user library and models tables

Revision ID: 11f4b571ad5f
Revises: a8f33880f435
Create Date: 2026-04-18 22:52:06.145683

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "11f4b571ad5f"
down_revision: Union[str, Sequence[str], None] = "a8f33880f435"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "libraries",
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("record_id", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("user_id", "record_id"),
    )
    op.create_table(
        "models",
        sa.Column("uri", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("model_name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("uri"),
    )
    op.create_table(
        "users",
        sa.Column("uri", sa.String(), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("password", sa.LargeBinary(), nullable=False),
        sa.Column("access_level", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("uri"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    op.drop_table("models")
    op.drop_table("libraries")
    # ### end Alembic commands ###
