"""removing index column, indexing artists

Revision ID: 3e00e2da9679
Revises: 26b7b9040dbe
Create Date: 2026-03-30 21:58:15.230923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e00e2da9679'
down_revision: Union[str, Sequence[str], None] = '26b7b9040dbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_music_repository_artists'), 'music_repository', ['artists'], unique=False)
    op.drop_column('music_repository', 'index')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('music_repository', sa.Column('index', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False))
    op.drop_index(op.f('ix_music_repository_artists'), table_name='music_repository')
    # ### end Alembic commands ###
