"""history multi user support

Revision ID: cfdef25cd9a2
Revises: 
Create Date: 2026-04-19 02:26:48.597543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfdef25cd9a2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('models', sa.Column('algorithm', sa.String(), nullable=True))
    op.add_column('music_history', sa.Column('user_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('music_history', 'user_id')
    op.drop_column('models', 'algorithm')
    # ### end Alembic commands ###
